### PR TITLE
fix vulnerable dependency

### PR DESCRIPTION
**Pull request by daniel-mcmullen**

### CODE REVIEW

**Comment by scytherswings** [comment]
Alright so the `Gemfile.lock` is just like node's package.lock file, if you want to change the installed version of a dependency you need to edit the `Gemfile`. This dependency is an interesting issue though since it's acquired through a few other libraries. I'll update the dependencies using `bundle update` and push my changes onto this branch, if you're cool with that.

**Comment by daniel-mcmullen** [comment]
Yeah you do you
  

  
  

  
  
>

**Comment by scytherswings** [comment]
lol cool

**Comment by scytherswings** [comment]
Oh, it looks like you forked the repo, that's why I can't find your branch lol. I'm going to close this and put up a pr to fix

**Pull request closed without merging**
